### ISSUE TITLE
Please hide a slack-token

### ISSUE THREAD

**Issue by tonilopezmr** [JoseLlorensRipolles/Slack-Bot-Python#1]
https://twitter.com/pedro_g_s/status/748513253005852672

Please hide the slack token, is very dangerous.

Copy the slack token y a file, and with .gitignore exclude that file to git, and in  your project, read the file to get the slack token.

Thanks!

**Comment by JoseLlorensRipolles** [comment]
Done! Now it must be defined as a environment variable.

![done](https://cloud.githubusercontent.com/assets/10089812/16509221/d03fca82-3f3a-11e6-80ff-a52869a7998d.gif)

**Comment by tonilopezmr** [comment]
Wow! so good! https://github.com/JoseLlorensRipolles/Slack-Bot-Python/commit/70fcea77903a9ab6e33f3c10c21f912adb796260 and the enviroment variable where is it?

**Comment by JoseLlorensRipolles** [comment]
You must set it. It's explained in the readme
